export type PublicLanguage = "en" | "fr";

const french: Record<string, string> = {
  "Continue with LinkedIn": "Continuer avec LinkedIn",
  "Sign in to continue using your LinkedIn account.": "Connectez-vous avec votre compte LinkedIn pour continuer.",
  "Sign in with LinkedIn": "Se connecter avec LinkedIn",
  "Signed in with LinkedIn": "Connecté avec LinkedIn",
  "Sign out": "Se déconnecter",
  "Checking sign-in…": "Vérification de la connexion…",
  "Opening LinkedIn…": "Ouverture de LinkedIn…",
  "LinkedIn sign-in is being configured. Please check back soon.": "La connexion LinkedIn est en cours de configuration. Revenez bientôt.",
  "Sign-in status couldn’t load. Try again.": "Impossible de vérifier la connexion. Réessayez.",
  "LinkedIn sign-in couldn’t be completed. Try again.": "La connexion LinkedIn n’a pas abouti. Réessayez.",
  "Allow popups to sign in with LinkedIn, then try again.": "Autorisez les fenêtres popup pour vous connecter avec LinkedIn, puis réessayez.",
  "Sign-out couldn’t be completed. Try again.": "La déconnexion n’a pas abouti. Réessayez.",
  "Try again": "Réessayer",
  "Choose a time in Patrick’s calendar.": "Choisissez un créneau dans le calendrier de Patrick.",
  "Patrick Chassany’s Calendly calendar": "Calendrier Calendly de Patrick Chassany",
  "Open calendar in a new tab": "Ouvrir le calendrier dans un nouvel onglet",
  "Sign in with LinkedIn to send Patrick a message.": "Connectez-vous avec LinkedIn pour envoyer un message à Patrick.",
  "Write your message before sending.": "Écrivez votre message avant de l’envoyer.",
  "Your LinkedIn session expired. Sign in again to send your message.": "Votre session LinkedIn a expiré. Reconnectez-vous pour envoyer votre message.",
  "Your message couldn’t be sent. Please try again.": "Votre message n’a pas pu être envoyé. Réessayez.",
  "Your message has been sent.": "Votre message a été envoyé.",
  "Write another message": "Écrire un autre message",
  "Message delivery is being configured. Your draft stays here.": "L’envoi de messages est en cours de configuration. Votre brouillon reste ici.",
  "Send message": "Envoyer le message",
  "Sending…": "Envoi en cours…",
  "Ask me anything": "Posez-moi vos questions",
  "Book a meeting": "Prendre rendez-vous",
  "Send a message": "Envoyer un message",
  "Connect with me": "Entrer en relation",
  "Patrick’s AI Collaborator.": "Le Collaborateur IA de Patrick.",
  "Let’s start a conversation.": "Commençons la conversation.",
  "Ask about his work. Share an idea. Find a time to talk. I’ll help you take the next step.": "Découvrez son travail. Partagez une idée. Trouvez un moment pour échanger. Je vous aide à préparer la suite.",
  "Unitalk gives you a public AI Collaborator that works for you. It remembers your context, handles entrusted work and involves you when your judgment matters. One conversation. Ask a question, book a call, or send a message — I'll handle it.": "Unitalk vous donne un Collaborateur IA public qui travaille pour vous. Il garde le contexte, prend en charge le travail confié et vous implique quand votre jugement compte. Une seule conversation. Posez une question, réservez un appel ou envoyez un message. Je m'en occupe.",
  "One conversation. Ask a question, book a call, or send a message — I'll handle it.": "Une seule conversation. Posez une question, réservez un appel ou envoyez un message. Je m'en occupe.",
  "Hi. I'm Patrick's AI Collaborator.\nWhat can I help you with?": "Bonjour. Je suis le Collaborateur IA de Patrick.\nQue puis-je faire pour vous ?",
  "I'd like to book a call": "Je voudrais réserver un appel",
  "Send a message to Patrick": "Envoyer un message à Patrick",
  "Why do you need an AI Collaborator?": "Pourquoi avez-vous besoin d'un Collaborateur IA ?",
  "Compare": "Comparer",
  "About Patrick and what he’s building at Unitalk": "À propos de Patrick et de ce qu’il construit chez Unitalk",
  "Hi. I’m Patrick’s AI Collaborator.\nWhat would you like to know?": "Bonjour. Je suis le Collaborateur IA de Patrick.\nQue souhaitez-vous savoir ?",
  "Log in": "Se connecter",
  "Create yours": "Créer le vôtre",
  "Open navigation": "Ouvrir la navigation",
  "Close navigation": "Fermer la navigation",
  "Patrick’s Collaborator navigation": "Navigation du Collaborateur de Patrick",
  "Patrick’s Collaborator mobile navigation": "Navigation mobile du Collaborateur de Patrick",
  "Choose how to interact with Patrick": "Choisir comment échanger avec Patrick",
  "Welcome back.": "Heureux de vous revoir.",
  "Your previous conversation is in this browser tab.": "Votre conversation précédente est conservée dans cet onglet.",
  "Continue conversation": "Reprendre la conversation",
  "Start a new conversation": "Commencer une nouvelle conversation",
  "Conversation with Patrick’s AI Collaborator": "Conversation avec le Collaborateur IA de Patrick",
  "You: ": "Vous : ",
  "Patrick’s AI Collaborator: ": "Le Collaborateur IA de Patrick : ",
  "Preparing a reply…": "Préparation d’une réponse…",
  "Suggested questions": "Questions suggérées",
  "What is Unitalk?": "Qu’est-ce que Unitalk ?",
  "Tell me about Patrick": "Parlez-moi de Patrick",
  "I have a partnership idea": "J’ai une idée de partenariat",
  "Ask Patrick’s AI Collaborator a question": "Poser une question au Collaborateur IA de Patrick",
  "What would you like to know?": "Que souhaitez-vous savoir ?",
  "Stop voice input": "Arrêter la dictée",
  "Use voice input": "Dicter une question",
  "Send question": "Envoyer la question",
  "Take this to Patrick": "Préparer un message pour Patrick",
  "Clear conversation": "Effacer la conversation",
  "Example replies · conversation kept in this tab only.": "Réponses d’exemple · conversation conservée dans cet onglet uniquement.",
  "Voice input isn’t supported in this browser. You can write your question instead.": "La dictée n’est pas disponible dans ce navigateur. Vous pouvez écrire votre question.",
  "Your words are in the message box. Review them, then send.": "Votre texte est dans le champ de message. Relisez-le avant de l’envoyer.",
  "Microphone access was not allowed. Enable it in your browser or write your question.": "L’accès au microphone a été refusé. Autorisez-le dans votre navigateur ou écrivez votre question.",
  "Voice input stopped. Try again or write your question.": "La dictée s’est arrêtée. Réessayez ou écrivez votre question.",
  "Listening. Speak, then review your draft before sending.": "À votre écoute. Dictez, puis relisez votre brouillon avant de l’envoyer.",
  "Voice input couldn’t start. Try again or write your question.": "La dictée n’a pas pu démarrer. Réessayez ou écrivez votre question.",
  "Demo": "Démo",
  "A little context makes a better conversation.": "Un peu de contexte pour un échange plus utile.",
  "1 of 3 · Your discussion": "1 sur 3 · Votre discussion",
  "2 of 3 · Choose a time": "2 sur 3 · Choisir un horaire",
  "3 of 3 · Your details": "3 sur 3 · Vos coordonnées",
  "Your meeting preview": "Votre aperçu de rendez-vous",
  "What would you like to discuss?": "De quoi souhaitez-vous parler ?",
  "An idea, a partnership, a project…": "Une idée, un partenariat, un projet…",
  "Anything to add?": "Quelque chose à ajouter ?",
  "Optional": "Facultatif",
  "Give Patrick a little background.": "Donnez un peu de contexte à Patrick.",
  "Add what you’d like to discuss.": "Indiquez le sujet de votre échange.",
  "Add your name and a valid email address.": "Indiquez votre nom et une adresse email valide.",
  "See example times": "Voir les horaires d’exemple",
  "Example slots · 30 minutes · Paris time": "Horaires d’exemple · 30 minutes · heure de Paris",
  "Edit discussion": "Modifier la discussion",
  "Your name": "Votre nom",
  "Your email": "Votre email",
  "Prepare meeting": "Préparer le rendez-vous",
  "Choose another time": "Choisir un autre horaire",
  "Meeting preview prepared.": "Aperçu de rendez-vous préparé.",
  "With": "Avec",
  "When": "Quand",
  "Discussion": "Discussion",
  "Context": "Contexte",
  "You": "Vous",
  "Edit meeting": "Modifier le rendez-vous",
  "Example times, not Patrick’s live calendar. No meeting is booked or invitation sent.": "Horaires d’exemple, indépendants de l’agenda de Patrick. Aucun rendez-vous n’est réservé ni aucune invitation envoyée.",
  "Something for Patrick personally? Put it into words.": "Un message personnel pour Patrick ? Préparons-le ensemble.",
  "Good connections start with a shared idea.": "Une bonne relation commence par une idée commune.",
  "You can find Patrick on LinkedIn, or prepare an introduction here.": "Retrouvez Patrick sur LinkedIn ou préparez une présentation ici.",
  "What brings us together?": "Qu’est-ce qui nous rapproche ?",
  "Exchange ideas": "Échanger des idées",
  "Explore a partnership": "Explorer un partenariat",
  "Work together": "Travailler ensemble",
  "Subject": "Objet",
  "What’s it about?": "De quoi s’agit-il ?",
  "Your message": "Votre message",
  "Introduce yourself": "Présentez-vous",
  "What are you working on? Where do our interests meet?": "Sur quoi travaillez-vous ? Quels sont nos intérêts communs ?",
  "What would you like Patrick to know?": "Que souhaitez-vous partager avec Patrick ?",
  "Include my questions from this conversation": "Inclure mes questions de cette conversation",
  "Review introduction": "Relire la présentation",
  "Review message": "Relire le message",
  "Add a valid email address.": "Indiquez une adresse email valide.",
  "Add your name.": "Indiquez votre nom.",
  "Write a little about what you have in mind.": "Décrivez ce que vous avez en tête.",
  "Introduction prepared.": "Présentation préparée.",
  "Message prepared.": "Message préparé.",
  "Your introduction to Patrick": "Votre présentation à Patrick",
  "Your message to Patrick": "Votre message à Patrick",
  "From": "De",
  "Purpose": "Objectif",
  "Your conversation context": "Le contexte de votre conversation",
  "Prepare introduction": "Préparer la présentation",
  "Prepare message": "Préparer le message",
  "Edit introduction": "Modifier la présentation",
  "Edit message": "Modifier le message",
  "Local preview. No introduction is sent or social account connected.": "Aperçu local. Aucune présentation n’est envoyée ni aucun compte social connecté.",
  "Local preview. Nothing is sent to Patrick.": "Aperçu local. Rien n'est envoyé à Patrick.",
  "Powered by": "Propulsé par",
  "Language": "Langue",
  "Opens a new tab": "Ouvre un nouvel onglet",
  "Patrick Chassany on LinkedIn": "Patrick Chassany sur LinkedIn",
  "What can I help you with?": "Que puis-je faire pour vous ?",
  "Suggested": "Suggestions",
  "Send": "Envoyer",
  "Let's find a time for you and Patrick.": "Trouvons un créneau pour vous et Patrick.",
  "Example times, not Patrick's live calendar. Nothing is booked.": "Horaires d'exemple, pas l'agenda réel de Patrick. Rien n'est réservé.",
  "I'll help you write a message to Patrick.": "Je vous aide à écrire un message à Patrick.",
  "What would you like to tell Patrick?": "Que voulez-vous dire à Patrick ?",
  "Just tell me what you have in mind — I'll turn it into a polished message.": "Dites-moi ce que vous avez en tête, j'en ferai un message soigné.",
  "Write a draft": "Rédiger un brouillon",
  "Local preview. Nothing is sent.": "Aperçu local. Rien n'est envoyé.",
  "Your draft — ready to review": "Votre brouillon — prêt à relire",
  "Shorter, more formal, add context…": "Plus court, plus formel, ajouter du contexte…",
  "Refine": "Affiner",
  "Looks good — prepare it": "C'est bon — préparer",
  "Write another": "Écrire un autre",
  "Add what you'd like to discuss.": "Ajoutez le sujet de votre rendez-vous.",
};

export function publicText(language: PublicLanguage, text: string): string {
  return language === "fr" ? french[text] ?? text : text;
}
