export const STORE_CATEGORIES = ["all", "apps", "tools", "skills", "collaborators"] as const;
export type StoreCategory = (typeof STORE_CATEGORIES)[number];

export const STORE_ENTRIES = [
  { id: "voicebox", category: "apps", title: "Voicebox", href: "https://github.com/unitalkai/voicebox", en: "A local voice studio for speech generation and dictation, with an API and MCP interface.", fr: "Un studio vocal local pour la génération de voix et la dictée, avec API et interface MCP.", originEn: "Public repository · upstream project: Jamie Pine / Voicebox", originFr: "Dépôt public · projet d’origine : Jamie Pine / Voicebox" },
  { id: "plugins", category: "tools", title: "Hermes plugins", href: "https://github.com/unitalkai/hermes-plugins", en: "Explore the Unitalk repository for Hermes extensions and inspect its source.", fr: "Explorez le dépôt Unitalk d’extensions Hermes et consultez son code.", originEn: "Unitalk · public repository", originFr: "Unitalk · dépôt public" },
  { id: "skills", category: "skills", title: "Unitalk Skills", href: "https://github.com/unitalkai/unitalk-skills", en: "Reusable skills for documents, analysis, writing, research and automation.", fr: "Des compétences réutilisables pour les documents, l’analyse, l’écriture, la recherche et l’automatisation.", originEn: "Unitalk · public skill collection", originFr: "Unitalk · collection publique de compétences" },
  { id: "seo", category: "collaborators", title: "SEO Auditor", href: "https://github.com/unitalkai/hermes-profile-seo-auditor", en: "A Hermes configuration for ongoing site audits and impact-ranked SEO reports.", fr: "Une configuration Hermes pour auditer un site en continu et classer les recommandations SEO par impact.", originEn: "Unitalk · Hermes profile distribution", originFr: "Unitalk · distribution de profil Hermes" },
  { id: "distributions", category: "collaborators", title: "Collaborator distributions", href: "https://github.com/unitalkai/profiles-distribution", en: "Package identity, skills, scheduled work and connections as a portable Hermes configuration.", fr: "Regroupez identité, compétences, travail planifié et connexions dans une configuration Hermes portable.", originEn: "Unitalk · public distribution reference", originFr: "Unitalk · référence publique de distribution" },
] as const;
