import { Icon } from "./icons";
import { localizedOffer, type MarketingLanguage } from "@/lib/marketing-language";
import { APPLICATION_OFFER } from "@/lib/collaborator-offer";
import "./marketing-faq.css";

export function MarketingFAQ({ language = "en" }: { language?: MarketingLanguage }) {
  const fr = language === "fr";
  const price = localizedOffer(language);
  const questions = fr ? [
    ["Qu’est-ce qu’un AI Collaborator ?", "Un Collaborateur IA est conçu pour gérer le suivi de vos relations : connaître le contact, retrouver les échanges, suivre les engagements et préparer le prochain pas. Vous définissez ses responsabilités et les décisions qui restent les vôtres."],
    ["En quoi est-il différent de ChatGPT, Claude ou Gemini ?", "Ces IA servent aussi au travail, avec des outils et des automatisations. La différence de Unitalk est la responsabilité continue d’une relation : un historique par contact, des prochaines étapes suivies et une même identité entre les canaux. Vous pouvez lui parler pour piloter ce suivi."],
    ["Pourquoi Unitalk plutôt que Hermes seul ?", "Hermes fournit le moteur autonome, la mémoire et les outils. Unitalk est conçu pour en faire une expérience de gestion des relations prête à utiliser : identité publique, continuité par contact, limites d’autorité, hébergement et exploitation accessibles. Les intégrations restent prévues sur ce site."],
    ["Combien coûte un Collaborateur ?", `${price.monthly} par mois ou ${price.annual} par an, soit 2 mois offerts. ${price.monthlyTokens} ${price.trialShort} Les applications hébergées sont facultatives.`],
    ["Que comprend l’essai et que se passe-t-il après les tokens inclus ?", `${price.trial} L’abonnement comprend ensuite 5 millions de tokens chaque mois. Les modèles éligibles, le décompte entrée/sortie, le report et le fonctionnement après épuisement restent à préciser. Aucun paiement ni supplément n’est activé dans cette expérience.`],
    ["Faut-il acheter Twenty ou Chatwoot ?", `Non. Le suivi des contacts et de leurs prochaines étapes est le rôle de base du Collaborateur. Twenty CRM ajoute une interface CRM complète ; Chatwoot Support ajoute un espace partagé de support. Chaque application hébergée et gérée coûte +${APPLICATION_OFFER.frenchMonthly}/mois. La connexion à votre compte SaaS existant est incluse côté Unitalk ; l’abonnement du fournisseur reste séparé. Ces options ne sont pas encore connectées ici.`],
    ["Puis-je utiliser mon abonnement ChatGPT ?", "Hermes propose une connexion avec un abonnement ChatGPT/Codex. Cette option n’est pas encore connectée à Unitalk. Les formules éligibles et leurs limites doivent être confirmées ; l’API OpenAI classique a sa propre facturation."],
    ["Qu’est-ce qui m’appartient ?", "Le modèle de Unitalk repose sur un Collaborateur qui vous appartient : son identité, ses connaissances, sa mémoire, ses compétences, ses outils et son autorité. Il est conçu pour rester portable lorsque vous changez d’hébergement ou de fournisseur IA."],
    ["Comment garder le contrôle ?", "DO IT pour agir dans vos limites, ASK ME pour demander votre accord, NEVER DO IT pour vos interdictions. Vous pouvez revoir ces règles, mettre en pause ou reprendre la main sur un échange."],
  ] : [
    ["What is an AI Collaborator?", "An AI Collaborator is designed to follow your relationships: know the contact, find past conversations, track commitments and prepare the next step. You define its responsibilities and the decisions that stay yours."],
    ["How is it different from ChatGPT, Claude or Gemini?", "These AI products are also used at work, with tools and automation. Unitalk’s difference is ongoing responsibility for a relationship: a history for each contact, tracked next steps and one identity across channels. Talking to your Collaborator is one way to direct that follow-up."],
    ["Why Unitalk rather than Hermes alone?", "Hermes provides the autonomous engine, memory and tools. Unitalk is designed to turn that into a ready-to-use relationship experience: public identity, contact continuity, clear authority, accessible hosting and operation. Integrations remain planned on this site."],
    ["How much does a Collaborator cost?", `${price.monthly} per month or ${price.annual} per year — 2 months free. ${price.monthlyTokens} ${price.trialShort} Hosted apps are optional.`],
    ["What is included in the trial and after the token allowance?", `${price.trial} The subscription then includes 5 million tokens each month. Eligible models, input/output counting, rollover and what happens when the allowance is used up are still to be specified. No payment or extra charge is activated in this experience.`],
    ["Do I need to buy Twenty or Chatwoot?", `No. Following contacts and their next steps is the Collaborator’s core role. Twenty CRM adds a full CRM interface; Chatwoot Support adds a shared support workspace. Each hosted and managed app costs +${APPLICATION_OFFER.monthly}/month. Connecting an existing SaaS account is included on Unitalk’s side; the provider subscription stays separate. These options are not connected here yet.`],
    ["Can I use my ChatGPT subscription?", "Hermes supports a ChatGPT/Codex subscription connection. This option is not yet connected to Unitalk. Eligible plans and limits still need to be confirmed; the standard OpenAI API has its own billing."],
    ["What do I own?", "Unitalk’s model is a Collaborator you own: its identity, knowledge, memory, skills, tools and authority. It is designed to stay portable when you change hosting or AI providers."],
    ["How do I stay in control?", "DO IT for work inside your boundaries, ASK ME for decisions that need approval, NEVER DO IT for hard limits. You can review the rules, pause or take over a conversation."],
  ];
  return <section id="faq" className="marketing-faq content-container" aria-labelledby="faq-title"><div className="faq-intro"><h2 id="faq-title">{fr ? <>Les questions.<br /><span>Les réponses.</span></> : <>A few questions.<br /><span>Clear answers.</span></>}</h2><p>{fr ? "Vos relations. L’offre. Ce qui vous appartient." : "Your relationships. The offer. What stays yours."}</p></div><div className="faq-questions">{questions.map(([question, answer]) => <details key={question} name="unitalk-faq"><summary>{question}<Icon name="plus" /></summary><p>{answer}</p></details>)}</div></section>;
}
