import Link from "next/link";
import { SiteHeader, SiteFooter } from "./site-shell";
import { EncounterLink } from "./collaborator-offer-context";
import { Icon } from "./icons";
import { marketingPath } from "@/lib/marketing-language";
import "./marketing-about.css";

export function MarketingAbout({ language = "en" }: { language?: "en" | "fr" }) {
  const fr = language === "fr";
  const layers = fr ? [
    ["Identité et voix", "Un nom, une présence publique et une voix. Une même identité, là où vous échangez.", null],
    ["Passerelle IA", "Choisissez les modèles et les fournisseurs qui donnent son intelligence à votre Collaborateur.", null],
    ["Mémoire Honcho", "Une mémoire conçue pour comprendre vos préférences, vos échanges et leurs liens dans la durée.", "https://www.honcho.dev"],
    ["Communications Stalwart", "Email, calendrier et contacts : une base de communication fondée sur des protocoles ouverts.", "https://stalw.art"],
    ["CRM Twenty · facultatif", "Une interface CRM complète, hébergée et gérée en option, ou connectée à votre compte existant.", "https://twenty.com"],
    ["Support Chatwoot · facultatif", "Un espace de support partagé, hébergé et géré en option, ou connecté à votre compte existant.", "https://www.chatwoot.com"],
    ["Applications, messageries, terminal", "Plusieurs façons de retrouver le même Collaborateur, son contexte et son travail.", null],
  ] : [
    ["Identity and voice", "A name, a public presence and a voice. The same identity wherever you interact.", null],
    ["AI gateway", "Choose the models and providers that power your Collaborator’s intelligence.", null],
    ["Honcho memory", "Memory designed to understand your preferences, conversations and relationships over time.", "https://www.honcho.dev"],
    ["Stalwart communications", "Email, calendar and contacts: a communication foundation built on open protocols.", "https://stalw.art"],
    ["Twenty CRM · optional", "A full CRM interface, optionally hosted and managed, or connected to your existing account.", "https://twenty.com"],
    ["Chatwoot support · optional", "A shared support workspace, optionally hosted and managed, or connected to your existing account.", "https://www.chatwoot.com"],
    ["Desktop, messaging and terminal", "Different ways to reach the same Collaborator, its context and its work.", null],
  ];
  return <div lang={language} className="marketing-home marketing-document about-page"><SiteHeader language={language} /><main id="main-content">
    <section className="about-hero content-container"><h1>{fr ? <>Un espace à vous.<br /><span>Une intelligence à vous.</span></> : <>A place of your own.<br /><span>Intelligence of your own.</span></>}</h1><p>{fr ? "La technologie change. La conviction reste : chacun doit pouvoir posséder ce qu’il construit." : "The technology changes. The belief stays: everyone should be able to own what they build."}</p><p>{fr ? "Hermes fournit le moteur. Unitalk est conçu pour rendre le suivi des relations prêt à utiliser : une identité publique, une histoire par contact et des prochaines étapes suivies. Les personnes et ce qui se passe avec elles sont au centre." : "Hermes provides the engine. Unitalk is designed to make relationship follow-up ready to use: a public identity, a history for each contact and tracked next steps. People and what happens with them are at the centre."}</p></section>
    <section className="about-founder content-container" aria-labelledby="founder-note"><div><h2 id="founder-note">{fr ? "Un mot de Patrick Chassany." : "A note from Patrick Chassany."}</h2><p className="about-byline">{fr ? "Fondateur de Unitalk" : "Founder of Unitalk"}</p></div><div className="about-prose"><p>{fr ? "En 1999, mon expérience chez AMEN était celle d’un bureau de vente de noms de domaine et d’hébergement de sites web. Nous rendions concret quelque chose qui paraissait encore technique : avoir son adresse et son espace sur Internet." : "In 1999, my experience at AMEN was selling domain names and website hosting. We made something that still seemed technical feel tangible: having your own address and your own place on the Internet."}</p><p>{fr ? "Aujourd’hui, je retrouve cette idée avec l’IA. Un modèle ne suffit pas. Il faut une identité, un endroit où fonctionner, de la mémoire, des outils et un moyen d’échanger. C’est ce que je veux rendre accessible avec Unitalk." : "Today, I see that same idea in AI. A model is not enough. It needs an identity, somewhere to run, memory, tools and a way to communicate. That is what I want to make accessible with Unitalk."}</p></div></section>
    <section className="about-comparison"><div className="content-container"><h2>{fr ? "La même intuition. Une nouvelle étape." : "The same idea. A new chapter."}</h2><div className="about-eras"><section><h3>AMEN · 1999</h3><p className="about-era-thesis">{fr ? "Votre adresse. Votre site." : "Your address. Your website."}</p><p>{fr ? "Un nom de domaine pour être trouvé. Un hébergement pour exister. Le point de départ d’un espace qui vous appartient." : "A domain name to be found. Hosting to have a presence. The starting point for a place that belongs to you."}</p></section><section><h3>Unitalk · {fr ? "Aujourd’hui" : "Today"}</h3><p className="about-era-thesis">{fr ? "Votre identité. Votre Collaborateur." : "Your identity. Your Collaborator."}</p><p>{fr ? "Une identité pour accueillir. Une mémoire pour garder le fil. Des outils pour travailler. Le point de départ d’une intelligence qui vous appartient." : "An identity to welcome people. Memory to keep the thread. Tools to work. The starting point for intelligence that belongs to you."}</p></section></div></div></section>
    <section className="about-architecture content-container"><div className="about-architecture-intro"><h2>{fr ? <>Hermes Agent.<br /><span>Augmenté.</span></> : <>Hermes Agent.<br /><span>Supercharged.</span></>}</h2><div><p>{fr ? "Le moteur autonome open source est le point de départ. Unitalk est conçu pour lui donner une vie professionnelle complète." : "The autonomous open-source engine is the starting point. Unitalk is designed to give it a complete professional life."}</p><a href="https://github.com/NousResearch/hermes-agent" className="text-link">{fr ? "Découvrir Hermes Agent" : "Explore Hermes Agent"}<Icon name="external" width="16" height="16" /></a></div></div><dl className="about-layers">{layers.map(([title, description, href]) => <div key={title}><dt>{href ? <a href={href}>{title}<Icon name="external" width="16" height="16" /></a> : title}</dt><dd>{description}</dd></div>)}</dl><p className="about-architecture-note">{fr ? "Cette architecture décrit la vision du produit. Hermes, Honcho, Stalwart, Twenty, Chatwoot et la passerelle IA ne sont pas encore connectés à ce site." : "This architecture describes the product vision. Hermes, Honcho, Stalwart, Twenty, Chatwoot and the AI gateway are not yet connected to this site."}</p></section>
    <section className="about-close content-container"><h2>{fr ? <>Un Collaborateur qui travaille pour vous.<br /><span>Et qui vous appartient.</span></> : <>A Collaborator that works for you.<br /><span>And belongs to you.</span></>}</h2><p>{fr ? "Commencez par une mission. Choisissez son intelligence, ses accès et l’endroit où il travaille." : "Start with one mission. Choose its intelligence, its access and where it works."}</p><div><EncounterLink language={language} marketing className="button button-primary">{fr ? "Commencer gratuitement" : "Start for free"}<Icon name="arrow" /></EncounterLink><Link className="text-link" href={marketingPath("/how-it-works", language)}>{fr ? "Comment ça marche" : "How it works"}<Icon name="arrow" /></Link></div></section>
  </main><SiteFooter language={language} /></div>;
}
